################################################################################
#
# lvgl_demo
#
################################################################################

LVGL_DEMO_SITE = $(TOPDIR)/../app/lvgl_demo
LVGL_DEMO_SITE_METHOD = local

# add dependencies
LVGL_DEMO_DEPENDENCIES += lvgl

LVGL_DEMO_INSTALL_STAGING = YES

ifeq ($(BR2_LVGL_DEMO_WIDGETS), y)
LVGL_DEMO_CONF_OPTS += -DLV_USE_DEMO_WIDGETS=1
endif

ifeq ($(BR2_LVGL_DEMO_KEYPAD_AND_ENCODER), y)
LVGL_DEMO_CONF_OPTS += -DLV_USE_DEMO_KEYPAD_AND_ENCODER=1
endif

ifeq ($(BR2_LVGL_DEMO_BENCHMARK), y)
LVGL_DEMO_CONF_OPTS += -DLV_USE_DEMO_BENCHMARK=1
endif

ifeq ($(BR2_LVGL_DEMO_STRESS), y)
LVGL_DEMO_CONF_OPTS += -DLV_USE_DEMO_STRESS=1
endif

ifeq ($(BR2_LVGL_DEMO_MUSIC), y)
LVGL_DEMO_CONF_OPTS += -DLV_USE_DEMO_MUSIC=1
endif

ifeq ($(BR2_LVGL_DEMO_RK_DEMO), y)
ifeq ($(BR2_RK_DEMO_ENABLE_MULTIMEDIA), y)
LVGL_DEMO_DEPENDENCIES += rockit rkadk
endif
ifeq ($(BR2_RK_DEMO_ENABLE_WIFIBT), y)
LVGL_DEMO_DEPENDENCIES += rkwifibt-app
endif
LVGL_DEMO_CONF_OPTS += -DRK_DEMO_MULTIMEDIA_EN=$(if $(BR2_RK_DEMO_ENABLE_MULTIMEDIA),1,0)
LVGL_DEMO_CONF_OPTS += -DRK_DEMO_SENSOR_EN=$(if $(BR2_RK_DEMO_ENABLE_SENSOR),1,0)
LVGL_DEMO_CONF_OPTS += -DRK_DEMO_WIFIBT_EN=$(if $(BR2_RK_DEMO_ENABLE_WIFIBT),1,0)
LVGL_DEMO_CONF_OPTS += -DRK_DEMO_ASR_EN=$(if $(BR2_RK_DEMO_ENABLE_ASR),1,0)
LVGL_DEMO_CONF_OPTS += -DLV_USE_RK_DEMO=1
endif

ifeq ($(BR2_LV_DRIVERS_USE_SDL_GPU), y)
LVGL_DEMO_CONF_OPTS += -DLV_DRV_USE_SDL_GPU=1
LVGL_DEMO_DEPENDENCIES += lv_drivers sdl2
endif

ifeq ($(BR2_LV_DRIVERS_USE_OPENGL), y)
LVGL_DEMO_CONF_OPTS += -DLV_DRV_USE_OPENGL=1
endif

ifeq ($(BR2_LV_DRIVERS_USE_DRM), y)
LVGL_DEMO_CONF_OPTS += -DLV_DRV_USE_DRM=1
LVGL_DEMO_DEPENDENCIES += lv_drivers libdrm libevdev
endif

ifeq ($(BR2_LV_DRIVERS_USE_RKADK), y)
LVGL_DEMO_CONF_OPTS += -DLV_DRV_USE_RKADK=1
LVGL_DEMO_DEPENDENCIES += lv_drivers rkadk rockchip-rga
endif

ifeq ($(BR2_PACKAGE_RK3506), y)
LVGL_DEMO_CONF_OPTS += -DLVGL_DEMO_RK3506=1
endif

$(eval $(cmake-package))
