#!/bin/sh

DIR_INIT=${1:-/etc/init.d}

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in ${DIR_INIT}/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

